apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5qv5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0042-tenant/cin4s-839-0042-app/devfile-sample-5qv5@sha256:01ba1bc2a96cbde9cd94b65e2fb97aa6ef3ee8f2af56d1f75db06460b234317c
        name: my-nodejs
        resources: {}
status: {}
